//
// Info.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Info: Codable, JSONEncodable, Hashable {

    public var version: String
    public var newsSites: [String]

    public init(version: String, newsSites: [String]) {
        self.version = version
        self.newsSites = newsSites
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case version
        case newsSites = "news_sites"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(version, forKey: .version)
        try container.encode(newsSites, forKey: .newsSites)
    }
}

